# Generated by Django 5.2.17 on 2026-09-01 06:54

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_feature_globalconnector_plan_planauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='billing_period',
            field=models.CharField(default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='parent_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_clients', to='api.client'),
        ),
        migrations.AddField(
            model_name='client',
            name='selected_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_coming_soon',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='globalconnector',
            name='is_coming_soon',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(default='UwoConnect Pro', max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=499.0, max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('TRIAL', 'Trial')], default='ACTIVE', max_length=20)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientWallet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_paise', models.BigIntegerField(default=0)),
                ('low_balance_threshold_paise', models.BigIntegerField(default=10000)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_threshold_paise', models.BigIntegerField(default=10000)),
                ('auto_recharge_amount_paise', models.BigIntegerField(default=50000)),
                ('saved_payment_method_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='UsageRate',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='IN', max_length=10)),
                ('service_category', models.CharField(choices=[('MARKETING', 'WhatsApp Marketing Message'), ('UTILITY', 'WhatsApp Utility Message'), ('AUTHENTICATION', 'WhatsApp Authentication Message'), ('SERVICE', 'WhatsApp Service Conversation'), ('AI_TOKENS', 'AI Completion Tokens')], max_length=30)),
                ('unit_price_paise', models.BigIntegerField(default=50)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('country_code', 'service_category', 'status')},
            },
        ),
        migrations.CreateModel(
            name='WalletLedger',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('type', models.CharField(choices=[('RECHARGE', 'Wallet Recharge'), ('USAGE', 'Usage Deduction'), ('REFUND', 'Refund Credit'), ('ADJUSTMENT', 'Manual Adjustment'), ('BONUS', 'Promotional Bonus')], max_length=20)),
                ('amount_paise', models.BigIntegerField()),
                ('balance_before_paise', models.BigIntegerField()),
                ('balance_after_paise', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('service_category', models.CharField(choices=[('WHATSAPP', 'WhatsApp Messaging'), ('AI', 'AI Processing'), ('SYSTEM', 'System / Platform'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger', to='api.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletRechargeOrder',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paise', models.BigIntegerField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_recharges', to='api.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
