# Generated by Django 5.2.17 on 2026-09-01 07:25

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_client_billing_period_client_is_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagerate',
            name='service_category',
            field=models.CharField(choices=[('MARKETING', 'WhatsApp Marketing Message'), ('UTILITY', 'WhatsApp Utility Message'), ('AUTHENTICATION', 'WhatsApp Authentication Message'), ('SERVICE', 'WhatsApp Service Conversation'), ('AI_TOKENS', 'AI Completion Tokens'), ('BROADCAST', 'Additional Broadcast Campaign')], max_length=30),
        ),
        migrations.AlterField(
            model_name='walletledger',
            name='service_category',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp Messaging'), ('AI', 'AI Processing'), ('BROADCAST', 'Broadcast Campaign'), ('SYSTEM', 'System / Platform'), ('GENERAL', 'General')], default='GENERAL', max_length=30),
        ),
        migrations.CreateModel(
            name='BroadcastEntitlement',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('billing_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('INCLUDED', 'Subscription Included'), ('PURCHASED', 'Wallet Purchased')], default='INCLUDED', max_length=20)),
                ('source', models.CharField(choices=[('SUBSCRIPTION', 'Subscription Plan'), ('WALLET', 'Prepaid Wallet')], default='SUBSCRIPTION', max_length=20)),
                ('included_quantity', models.IntegerField(default=1)),
                ('used_quantity', models.IntegerField(default=0)),
                ('remaining_quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('EXHAUSTED', 'Exhausted'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded')], db_index=True, default='AVAILABLE', max_length=20)),
                ('price_paise', models.BigIntegerField(default=0)),
                ('wallet_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_entitlements', to='api.client')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_entitlements', to='api.clientsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastUsage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_id', models.CharField(db_index=True, max_length=100)),
                ('amount_paise', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='EXECUTED', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_usages', to='api.client')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.broadcastentitlement')),
                ('wallet_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_usages', to='api.walletledger')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
