# Generated by Django 5.2.17 on 2026-09-04 12:15

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_usagerate_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, default='1.0', max_length=20),
        ),
        migrations.CreateModel(
            name='QrAuthSession',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('WAITING', 'Waiting'), ('SCANNED', 'Scanned'), ('AUTHENTICATING', 'Authenticating'), ('AUTHENTICATED', 'Authenticated'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='CREATED', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_auth_sessions', to='api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
