# Generated by Django 5.2.17 on 2026-09-08 11:13

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_user_privacy_accepted_user_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='stage',
            field=models.CharField(choices=[('NEW', 'New Lead'), ('QUALIFIED', 'Qualified Lead'), ('HOT_LEAD', '🔥 Hot Lead'), ('FOLLOWUP', 'Follow Up'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Closed Won'), ('LOST', 'Closed Lost')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='ContactFollowUp',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Phone Call'), ('MESSAGE', 'WhatsApp / Message'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('OTHER', 'Other')], default='CALL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_follow_ups', to='api.client')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='api.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
    ]
