# Generated by Django 5.2.17 on 2026-09-08 12:24

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_add_contact_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrauthsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='auth_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='device_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrauthsession',
            name='user_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrauthsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('WAITING', 'Waiting'), ('SCANNED', 'Scanned'), ('AUTHENTICATING', 'Authenticating'), ('AUTHENTICATED', 'Authenticated'), ('CONSUMED', 'Consumed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='WAITING', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrauthsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_auth_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LinkedDevice',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=150)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('token_hash', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_devices', to='api.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-linked_at'],
            },
        ),
    ]
