# Generated by Django 5.2.17 on 2026-09-09 10:02

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_qr_device_linking'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('custom', 'Custom')], default='light', max_length=20)),
                ('primary_color', models.CharField(blank=True, default='#059669', max_length=20)),
                ('accent_color', models.CharField(blank=True, default='#0d9488', max_length=20)),
                ('language', models.CharField(default='en', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
