# Generated by Django 5.2.17 on 2026-09-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrauthsession',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True),
        ),
    ]
