# Generated by Django 5.2.17 on 2026-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_add_short_code_to_qrauthsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meta_portfolio_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
