# Generated by Django 5.2.17 on 2026-09-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_user_meta_portfolio_eligible'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='meta_portfolio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='meta_portfolio_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
