# Generated by Django 5.2.17 on 2026-09-14 09:03

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_client_meta_portfolio_name_user_meta_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_version',
            field=models.CharField(blank=True, default='1.0', max_length=20),
        ),
        migrations.CreateModel(
            name='LegalDocumentVersion',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('TERMS', 'Terms & Conditions'), ('PRIVACY_POLICY', 'Privacy Policy')], max_length=30)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_reconsent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_date', '-version'],
                'unique_together': {('document_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='UserLegalConsent',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=30)),
                ('document_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
    ]
