"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import sys
import firebase_admin
from firebase_admin import credentials

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env
env_path = os.path.join(BASE_DIR, '.env')
load_dotenv(env_path, override=True)

# Initialize Firebase Admin SDK
import json

firebase_sa_json = os.getenv('FIREBASE_SERVICE_ACCOUNT_JSON')
firebase_sa_path = os.getenv('FIREBASE_SERVICE_ACCOUNT_PATH', '')

if not firebase_admin._apps:
    try:
        if firebase_sa_json:
            cred = credentials.Certificate(json.loads(firebase_sa_json))
            firebase_admin.initialize_app(cred)
        elif firebase_sa_path:
            if not os.path.isabs(firebase_sa_path):
                firebase_sa_path = os.path.join(BASE_DIR, firebase_sa_path)
            if os.path.exists(firebase_sa_path):
                cred = credentials.Certificate(firebase_sa_path)
                firebase_admin.initialize_app(cred)
            else:
                firebase_admin.initialize_app()
        else:
            firebase_admin.initialize_app()
    except Exception as e:
        print(f"[WARNING] Firebase Admin init warning: {e}")

# SECURITY: Load secret key from environment, fallback to dev key only in DEBUG mode
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('DEBUG', 'True') == 'True':
        SECRET_KEY = 'django-insecure-dev-local-key-change-in-production'
    else:
        raise ValueError("CRITICAL: SECRET_KEY environment variable is required in production.")

DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Host header validation
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = [
        'localhost',
        '127.0.0.1',
        'uwoconnect.aisa24.com',
        '.aisa24.com',
        '.run.app',
        '.azurewebsites.net',
    ]

# Application definition
INSTALLED_APPS = [
    'daphne',
    'mongo_migrations.apps.MongoAuthConfig',
    'mongo_migrations.apps.MongoContentTypesConfig',
    'mongo_migrations.apps.MongoSessionsConfig',
    'django.contrib.staticfiles',
    
    # Third party
    'django_mongodb_backend',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'channels',

    # Local
    'api',
]

from datetime import timedelta
SIMPLE_JWT = {
    'SIGNING_KEY': SECRET_KEY,
    'ALGORITHM': 'HS256',
    'USER_ID_CLAIM': 'user_id',
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'api.middleware.SecurityAntiCacheMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'api.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'api.services.jwt_auth.JWTQueryParamAuthentication',
        'api.services.firebase_auth.FirebaseAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'api.renderers.MongoJSONRenderer',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
}

# Use MongoDB ObjectId as default PK for all models
DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

# Point Django built-in apps to our MongoDB-compatible migrations
MIGRATION_MODULES = {
    'auth': 'mongo_migrations.auth',
    'contenttypes': 'mongo_migrations.contenttypes',
    'sessions': 'mongo_migrations.sessions',
}

# CORS Configuration: Enforce allowed origins with support for custom white-label domains
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL', 'True').lower() in ('true', '1') if DEBUG else False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.run\.app$",
    r"^https://.*\.aisa24\.com$",
    r"^https://.*\.azurewebsites\.net$",
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*$",  # Allow custom white-label agency HTTPS domains
    r"^http://(192\.168\.\d+\.\d+|10\.\d+\.\d+\.\d+|172\.(1[6-9]|2\d|3[0-1])\.\d+\.\d+)(:\d+)?$",
]
CORS_ALLOWED_ORIGINS = [
    'https://uwoconnect.aisa24.com',
    'https://uwoconnectforf-743978421487.asia-south1.run.app',
    'https://uwoconnectforf-743928421487.asia-south1.run.app',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8080',
    'http://192.168.29.228:3000',
    'http://192.168.29.24:3000',
]

# CSRF trusted origins — required for POST requests in production (DEBUG=False)
CSRF_TRUSTED_ORIGINS = [
    'https://*.run.app',
    'https://*.aisa24.com',
    'https://*.azurewebsites.net',
    'https://*.azurestaticapps.net',
    'https://*.vercel.app',
    'https://*.ngrok-free.app',
    'https://uwoconnectforb-743978421487.asia-south1.run.app',
    'https://uwoconnectforf-743978421487.asia-south1.run.app',
    'https://uwoconnectforb-743928421487.asia-south1.run.app',
    'https://uwoconnectforf-743928421487.asia-south1.run.app',
    'https://aisaconnectback-anaqbuapb6c6apgy.centralindia-01.azurewebsites.net',
    'https://uwoconnect.aisa24.com',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:8080',
    'http://192.168.29.228:3000',
]

# Security Headers & Hardening for CASA Compliance
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
            ],
        },
    },
]

ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database — MongoDB Atlas via django-mongodb-backend
DEFAULT_MONGO_URI = 'mongodb+srv://admin_db_user:admin%40123@cluster0.drmnlav.mongodb.net/?appName=Cluster0&tlsAllowInvalidCertificates=true'
mongo_uri = os.getenv('MONGODB_URI', DEFAULT_MONGO_URI)
if not mongo_uri:
    if DEBUG:
        mongo_uri = 'mongodb://localhost:27017/'
    else:
        raise ValueError("CRITICAL: MONGODB_URI environment variable is required.")

# In production mode, strip tlsAllowInvalidCertificates parameter if present
if not DEBUG and 'tlsAllowInvalidCertificates=true' in mongo_uri:
    mongo_uri = mongo_uri.replace('&tlsAllowInvalidCertificates=true', '').replace('tlsAllowInvalidCertificates=true&', '').replace('?tlsAllowInvalidCertificates=true', '')

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': os.getenv('MONGODB_DB_NAME', 'aisaconnect_db_v5'),
        'HOST': mongo_uri,
        'CONN_MAX_AGE': 60,
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

if os.getenv('GS_BUCKET_NAME'):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME')
    GS_PROJECT_ID = os.getenv('GS_PROJECT_ID')
elif os.getenv('AZURE_ACCOUNT_NAME'):
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.azure_storage.AzureStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
    AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
    AZURE_CONTAINER = os.getenv('AZURE_CONTAINER', 'media')
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Email Configuration
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@uwoconnect.app')

if EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    # Fallback: print to console if no email credentials set
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Cashfree Payment Gateway Settings
CASHFREE_APP_ID = os.getenv('CASHFREE_APP_ID', '')
CASHFREE_SECRET_KEY = os.getenv('CASHFREE_SECRET_KEY', '')
CASHFREE_ENV = os.getenv('CASHFREE_ENV', 'TEST')

# Razorpay Payment Gateway Settings
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.getenv('RAZORPAY_WEBHOOK_SECRET', '')

# Channels Layer configuration
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}



