from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView, LoginView, GoogleLoginView, GoogleClientIdView, FirebaseLoginView, UWOLoginView, ClientViewSet, AutomationViewSet, WorkflowViewSet, 

    ContactViewSet, AdminStatsView, ClientStatsView, AdminAutomationsView, AdminMessagesView, 
    WhatsAppWebhookView, FacebookInstagramWebhookView, AdminUsersView, ProfileView, ClientMessagesView, MediaProxyView,
    GlobalSettingsView, PlatformAssistantView, KnowledgeBaseView, TemplateViewSet, 
    CampaignViewSet, ForgotPasswordSendOTPView, ForgotPasswordVerifyOTPView, ForgotPasswordResetView,
    SupportMessageViewSet, AdminImpersonateView, AuditLogViewSet,
    SuggestDraftView, TeamMemberViewSet, TeamInviteView, TeamInviteQRView, TeamInviteValidateView, TeamChatView, ProductViewSet, OrderViewSet,
    CreatePaymentOrderView, VerifyPaymentView, PaymentHistoryView, CashfreeWebhookView, RazorpayWebhookView,
    WhatsAppEmbeddedSignupView, GmailConnectView, GmailCallbackView, GmailSyncView, GmailDisconnectView, YouTubeConnectView, YouTubeCallbackView, YouTubeStatusView, YouTubeSyncView, YouTubeAnalyticsView, YouTubeVideosView, YouTubeCommentsView, YouTubeSettingsView, YouTubeCheckNewView, YouTubeUploadView, YouTubeChannelProfileView, YouTubeDeleteView, YouTubeAISuggestReplyView,
    InstagramEmbeddedSignupView, FacebookEmbeddedSignupView, InstagramOAuthCallbackView,
    ProjectViewSet, TaskViewSet, WorkReportView, WorkApprovalView, TeamChannelView,
    TeamChatMessageView, TeamAnalyticsView, TeamAICopilotView, AttendanceViewSet, LeaveRequestViewSet,
    OneDriveConnectView, OneDriveCallbackView, OneDriveStatusView, OneDriveSyncView, OneDriveDisconnectView,
    GoogleCalendarConnectView, GoogleCalendarCallbackView, GoogleCalendarStatusView, GoogleCalendarSyncView, GoogleCalendarCreateEventView, GoogleCalendarDisconnectView,
    GoogleSheetsConnectView, GoogleSheetsCallbackView, GoogleSheetsStatusView, GoogleSheetsSyncView, GoogleSheetsAppendRowView, GoogleSheetsDisconnectView,
    GoogleDocsConnectView, GoogleDocsCallbackView, GoogleDocsStatusView, GoogleDocsSyncView, GoogleDocsCreateDocView, GoogleDocsDisconnectView,
    GoogleSlidesConnectView, GoogleSlidesCallbackView, GoogleSlidesStatusView, GoogleSlidesSyncView, GoogleSlidesCreatePresentationView, GoogleSlidesDisconnectView,
    PublicCalendarSlotsView, PublicCalendarBookView,
    ConversationViewSet, MonitoringStatsView, MonitoringAnalyticsView,
    GoogleNewsSettingsView, GoogleNewsFeedView, GoogleNewsAISummarizeView, GoogleNewsSendAlertView,
    GuideViewSet, GuideSectionDetailView, GuideStepDetailView, GuideProgressView,
    OutlookConnectView, OutlookCallbackView, OutlookStatusView, OutlookSyncView, OutlookSendMailView, OutlookDisconnectView,
    OutlookCalendarEventsView, OutlookTeamsView, OutlookContactsView, OutlookExcelView,
    EmailAccountViewSet, EmailMessageViewSet, EmailAutoReplyViewSet, EmailAutomationWorkflowViewSet, EmailAnalyticsView, EmailComposeView,
    WebRTCIceConfigView, WebRTCInitiateCallView, WebRTCCallSignalView, WebRTCHistoryView,
    WebRTCActiveCallCheckView, WebRTCCallActionView,
    CallScheduleView, CallAISummaryView, CallAnalyticsView, HealthCheckView,
    RazorpayOAuthInitiateView, RazorpayOAuthCallbackView, RazorpayConnectionStatusView,
    RazorpayModeSwitchView, PublicProductCheckoutInfoView, ProductCheckoutCreateOrderView,
    ProductCheckoutVerifyView, ProductCheckoutWebhookView, ClientProductSalesView,
    ClientSalesDashboardView, ClientRefundView,
    SuperAdminOverviewView, SuperAdminClientsListView, SuperAdminClientDetailDashboardView,
    SuperAdminClientActionView, SuperAdminTeamListView, SuperAdminChannelsListView, SuperAdminTeamSummaryView,
    SuperAdminMessagesListView, SuperAdminSalesListView, SuperAdminQuotationsListView,
    SuperAdminProposalsListView, SuperAdminInvoicesListView, SuperAdminReportsListView,
    SuperAdminProductsListView,
    SuperAdminGlobalSearchView, SuperAdminProjectsListView, SuperAdminProjectDetailView,
    SuperAdminProjectAssignMembersView, SuperAdminAllTeamsView, SuperAdminTeamChannelDetailView,
    SuperAdminTeamChannelAssignMembersView, SuperAdminMemberDetailView, SuperAdminTeamAnalyticsView,
    ClientIntelligenceStatsView, ClientIntelligenceListView, ClientIntelligenceDetailView,
    ClientIntelligenceActionView, ClientIntelligenceExportView,
    AdminGlobalConnectorsView,
    AdminChannelAccessMatrixView, AdminClientChannelAccessDetailView,
    AdminBulkChannelAccessView, AdminChannelAuditLogsView, AdminChannelAuditLogView,
    EffectiveConnectorsView, GlobalConnectorsStatusView
)
from .views.plan_management_views import FeatureViewSet, PlanViewSet, PlanFeatureViewSet, ClientFeatureOverrideViewSet, PlanAuditLogViewSet, ClientEntitlementsView
from api.views.zoho_views import ZohoConnectView, ZohoCallbackView, ZohoDisconnectView, ZohoTestLeadView

from .views.sales_document_views import (
    SalesDocumentViewSet, SalesDocumentTemplateViewSet, SalesAnalyticsView,
    PublicSalesDocumentView, PublicSalesDocumentAcceptView,
    PublicSalesDocumentRejectView, PublicSalesDocumentPDFView
)
from .views.invoice_views import InvoiceViewSet, PublicInvoiceView, PublicInvoicePDFView

router = DefaultRouter()
router.register(r'clients', ClientViewSet, basename='client')
router.register(r'automations', AutomationViewSet, basename='automation')
router.register(r'workflows', WorkflowViewSet, basename='workflow')
router.register(r'contacts', ContactViewSet, basename='contact')
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'templates', TemplateViewSet, basename='template')
router.register(r'campaigns', CampaignViewSet, basename='campaign')
router.register(r'support/messages', SupportMessageViewSet, basename='support-message')
router.register(r'audit-logs', AuditLogViewSet, basename='audit-log')
router.register(r'team/members', TeamMemberViewSet, basename='team-member')
router.register(r'team/projects', ProjectViewSet, basename='team-project')
router.register(r'team/tasks', TaskViewSet, basename='team-task')
router.register(r'team/attendance', AttendanceViewSet, basename='team-attendance')
router.register(r'team/leaves', LeaveRequestViewSet, basename='team-leave')
router.register(r'products', ProductViewSet, basename='product')
router.register(r'orders', OrderViewSet, basename='order')
router.register(r'guides', GuideViewSet, basename='guide')
router.register(r'email/accounts', EmailAccountViewSet, basename='email-account')
router.register(r'email/messages', EmailMessageViewSet, basename='email-message')
router.register(r'email/auto-replies', EmailAutoReplyViewSet, basename='email-auto-reply')
router.register(r'email/automations', EmailAutomationWorkflowViewSet, basename='email-automation')
router.register(r'sales-documents', SalesDocumentViewSet, basename='sales-document')
router.register(r'sales-document-templates', SalesDocumentTemplateViewSet, basename='sales-document-template')
router.register(r'invoices', InvoiceViewSet, basename='invoice')
router.register(r'quotations', SalesDocumentViewSet, basename='quotation')
router.register(r'proposals', SalesDocumentViewSet, basename='proposal')
router.register(r'features', FeatureViewSet, basename='feature')
router.register(r'plans', PlanViewSet, basename='plan')
router.register(r'plan-features', PlanFeatureViewSet, basename='plan-feature')
router.register(r'client-feature-overrides', ClientFeatureOverrideViewSet, basename='client-feature-override')
router.register(r'plan-audit-logs', PlanAuditLogViewSet, basename='plan-audit-log')

urlpatterns = [
    path('plans/public/', PlanViewSet.as_view({'get': 'public_plans'}), name='public-plans'),
    path('plans/public', PlanViewSet.as_view({'get': 'public_plans'})),
    path('client/entitlements/', ClientEntitlementsView.as_view(), name='client-entitlements'),
    path('client/entitlements', ClientEntitlementsView.as_view()),
    path('client/select-channel/', ClientEntitlementsView.as_view(), name='client-select-channel'),
    path('client/select-channel', ClientEntitlementsView.as_view()),
    path('client/subscribe/', ClientEntitlementsView.as_view(), name='client-subscribe'),
    path('client/subscribe', ClientEntitlementsView.as_view()),
    path('', include(router.urls)),
    path('health', HealthCheckView.as_view(), name='health-check'),
    path('health/', HealthCheckView.as_view(), name='health-check-slash'),
    path('email/analytics/', EmailAnalyticsView.as_view(), name='email-analytics'),
    path('guides/progress/', GuideProgressView.as_view(), name='guide-progress-list'),
    path('guides/progress/<slug:slug>/', GuideProgressView.as_view(), name='guide-progress-detail'),
    path('guides/sections/<int:section_id>/', GuideSectionDetailView.as_view(), name='guide-section-detail'),
    path('guides/steps/<int:step_id>/', GuideStepDetailView.as_view(), name='guide-step-detail'),
    path('monitoring/stats/', MonitoringStatsView.as_view(), name='monitoring-stats'),
    path('monitoring/analytics/', MonitoringAnalyticsView.as_view(), name='monitoring-analytics'),
    path('team/invites/', TeamInviteView.as_view(), name='team-invites'),
    path('team/invites/generate-qr/', TeamInviteQRView.as_view(), name='team-invite-qr'),
    path('team/invites/validate/', TeamInviteValidateView.as_view(), name='team-invite-validate'),
    path('team/chat/', TeamChatView.as_view(), name='team-chat'),
    path('team/reports/', WorkReportView.as_view(), name='team-reports'),
    path('team/approvals/', WorkApprovalView.as_view(), name='team-approvals'),
    path('team/channels/', TeamChannelView.as_view(), name='team-channels'),
    path('team/channel-messages/', TeamChatMessageView.as_view(), name='team-channel-messages'),
    path('team/analytics/', TeamAnalyticsView.as_view(), name='team-analytics'),
    path('team/ai-copilot/', TeamAICopilotView.as_view(), name='team-ai-copilot'),
    path('auth/register', RegisterView.as_view(), name='register'),
    path('auth/login', LoginView.as_view(), name='login'),
    path('auth/google-login', GoogleLoginView.as_view(), name='google-login'),
    path('auth/google-client-id', GoogleClientIdView.as_view(), name='google-client-id'),
    path('auth/gmail/connect', GmailConnectView.as_view(), name='gmail-connect'),
    path('auth/gmail/callback', GmailCallbackView.as_view(), name='gmail-callback'),
    path('auth/gmail/disconnect', GmailDisconnectView.as_view(), name='gmail-disconnect'),
    path('auth/google-calendar/connect', GoogleCalendarConnectView.as_view(), name='google-calendar-connect'),
    path('auth/google-calendar/callback', GoogleCalendarCallbackView.as_view(), name='google-calendar-callback'),
    path('auth/gmail/sync', GmailSyncView.as_view(), name='gmail-sync'),
    path('auth/firebase-login', FirebaseLoginView.as_view(), name='firebase-login'),
    path('auth/uwo-login', UWOLoginView.as_view(), name='uwo-login'),

    path('auth/forgot-password/send-otp', ForgotPasswordSendOTPView.as_view(), name='forgot-password-send-otp'),
    path('auth/forgot-password/verify-otp', ForgotPasswordVerifyOTPView.as_view(), name='forgot-password-verify-otp'),
    path('auth/forgot-password/reset', ForgotPasswordResetView.as_view(), name='forgot-password-reset'),
    path('auth/whatsapp/embedded-signup', WhatsAppEmbeddedSignupView.as_view(), name='whatsapp-embedded-signup'),
    path('auth/instagram/embedded-signup', InstagramEmbeddedSignupView.as_view(), name='instagram-embedded-signup'),
    path('auth/facebook/embedded-signup', FacebookEmbeddedSignupView.as_view(), name='facebook-embedded-signup'),
    path('auth/instagram/oauth-callback', InstagramOAuthCallbackView.as_view(), name='instagram-oauth-callback'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('profile/', ProfileView.as_view()),
    path('media-proxy/', MediaProxyView.as_view(), name='media-proxy'),
    path('messages/', ClientMessagesView.as_view(), name='client-messages'),
    path('messages/suggest_draft/', SuggestDraftView.as_view(), name='suggest-draft'),
    path('client/stats', ClientStatsView.as_view(), name='client-stats'),
    path('client/entitlements', ClientEntitlementsView.as_view(), name='client-entitlements'),
    path('client/entitlements/', ClientEntitlementsView.as_view()),
    path('admin/stats', AdminStatsView.as_view(), name='admin-stats'),
    path('admin/clients/overview', ClientIntelligenceListView.as_view(), name='admin-clients-overview'),
    path('admin/clients/overview/', ClientIntelligenceListView.as_view()),
    path('admin/clients/<str:client_id>/details', ClientIntelligenceDetailView.as_view(), name='admin-clients-details'),
    path('admin/clients/<str:client_id>/details/', ClientIntelligenceDetailView.as_view()),
    path('admin/client-intelligence/stats', ClientIntelligenceStatsView.as_view(), name='client-intelligence-stats'),
    path('admin/client-intelligence/stats/', ClientIntelligenceStatsView.as_view()),
    path('admin/client-intelligence/clients', ClientIntelligenceListView.as_view(), name='client-intelligence-clients'),
    path('admin/client-intelligence/clients/', ClientIntelligenceListView.as_view()),
    path('admin/client-intelligence/clients/<str:client_id>', ClientIntelligenceDetailView.as_view(), name='client-intelligence-detail'),
    path('admin/client-intelligence/clients/<str:client_id>/', ClientIntelligenceDetailView.as_view()),
    path('admin/client-intelligence/clients/<str:client_id>/action', ClientIntelligenceActionView.as_view(), name='client-intelligence-action'),
    path('admin/client-intelligence/clients/<str:client_id>/action/', ClientIntelligenceActionView.as_view()),
    path('admin/client-intelligence/export', ClientIntelligenceExportView.as_view(), name='client-intelligence-export'),
    path('admin/client-intelligence/export/', ClientIntelligenceExportView.as_view()),
    path('admin/overview', SuperAdminOverviewView.as_view(), name='super-admin-overview'),
    path('admin/overview/', SuperAdminOverviewView.as_view()),
    path('admin/clients-directory', SuperAdminClientsListView.as_view(), name='super-admin-clients-directory'),
    path('admin/clients-directory/', SuperAdminClientsListView.as_view()),
    path('admin/clients/<str:client_id>/dashboard', SuperAdminClientDetailDashboardView.as_view(), name='super-admin-client-dashboard'),
    path('admin/clients/<str:client_id>/dashboard/', SuperAdminClientDetailDashboardView.as_view()),
    path('admin/clients/<str:client_id>/action', SuperAdminClientActionView.as_view(), name='super-admin-client-action'),
    path('admin/clients/<str:client_id>/action/', SuperAdminClientActionView.as_view()),
    path('admin/all-team', SuperAdminTeamListView.as_view(), name='super-admin-all-team'),
    path('admin/all-team/', SuperAdminTeamListView.as_view()),
    path('admin/all-team/create', SuperAdminMemberDetailView.as_view(), name='super-admin-member-create'),
    path('admin/all-team/create/', SuperAdminMemberDetailView.as_view()),
    path('admin/all-team/<str:member_id>', SuperAdminMemberDetailView.as_view(), name='super-admin-member-detail'),
    path('admin/all-team/<str:member_id>/', SuperAdminMemberDetailView.as_view()),
    path('admin/team-summary', SuperAdminTeamSummaryView.as_view(), name='super-admin-team-summary'),
    path('admin/team-summary/', SuperAdminTeamSummaryView.as_view()),
    path('admin/team-analytics', SuperAdminTeamAnalyticsView.as_view(), name='super-admin-team-analytics'),
    path('admin/team-analytics/', SuperAdminTeamAnalyticsView.as_view()),
    path('admin/team/analytics', SuperAdminTeamAnalyticsView.as_view()),
    path('admin/team/analytics/', SuperAdminTeamAnalyticsView.as_view()),
    path('admin/all-projects', SuperAdminProjectsListView.as_view(), name='super-admin-all-projects'),
    path('admin/all-projects/', SuperAdminProjectsListView.as_view()),
    path('admin/all-projects/<str:project_id>', SuperAdminProjectDetailView.as_view(), name='super-admin-project-detail'),
    path('admin/all-projects/<str:project_id>/', SuperAdminProjectDetailView.as_view()),
    path('admin/all-projects/<str:project_id>/assign-members', SuperAdminProjectAssignMembersView.as_view(), name='super-admin-project-assign-members'),
    path('admin/all-projects/<str:project_id>/assign-members/', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-projects/<str:project_id>/members', SuperAdminProjectAssignMembersView.as_view(), name='super-admin-project-members'),
    path('admin/all-projects/<str:project_id>/members/', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-projects/<str:project_id>/members/<str:member_id>', SuperAdminProjectAssignMembersView.as_view(), name='super-admin-project-member-remove'),
    path('admin/all-projects/<str:project_id>/members/<str:member_id>/', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-teams', SuperAdminAllTeamsView.as_view(), name='super-admin-all-teams'),
    path('admin/all-teams/', SuperAdminAllTeamsView.as_view()),
    path('admin/all-teams/<str:channel_id>', SuperAdminTeamChannelDetailView.as_view(), name='super-admin-team-channel-detail'),
    path('admin/all-teams/<str:channel_id>/', SuperAdminTeamChannelDetailView.as_view()),
    path('admin/all-teams/<str:channel_id>/assign-members', SuperAdminTeamChannelAssignMembersView.as_view(), name='super-admin-team-channel-assign-members'),
    path('admin/all-teams/<str:channel_id>/assign-members/', SuperAdminTeamChannelAssignMembersView.as_view()),
    path('admin/all-channels', SuperAdminChannelsListView.as_view(), name='super-admin-all-channels'),
    path('admin/all-channels/', SuperAdminChannelsListView.as_view()),
    path('admin/all-messages', SuperAdminMessagesListView.as_view(), name='super-admin-all-messages'),
    path('admin/all-messages/', SuperAdminMessagesListView.as_view()),
    path('admin/all-sales', SuperAdminSalesListView.as_view(), name='super-admin-all-sales'),
    path('admin/all-sales/', SuperAdminSalesListView.as_view()),
    path('admin/all-quotations', SuperAdminQuotationsListView.as_view(), name='super-admin-all-quotations'),
    path('admin/all-quotations/', SuperAdminQuotationsListView.as_view()),
    path('admin/all-proposals', SuperAdminProposalsListView.as_view(), name='super-admin-all-proposals'),
    path('admin/all-proposals/', SuperAdminProposalsListView.as_view()),
    path('admin/all-invoices', SuperAdminInvoicesListView.as_view(), name='super-admin-all-invoices'),
    path('admin/all-invoices/', SuperAdminInvoicesListView.as_view()),
    path('admin/all-reports', SuperAdminReportsListView.as_view(), name='super-admin-all-reports'),
    path('admin/all-reports/', SuperAdminReportsListView.as_view()),
    path('admin/all-products', SuperAdminProductsListView.as_view(), name='super-admin-all-products'),
    path('admin/all-products/', SuperAdminProductsListView.as_view()),
    path('admin/global-search', SuperAdminGlobalSearchView.as_view(), name='super-admin-global-search'),
    path('admin/global-search/', SuperAdminGlobalSearchView.as_view()),
    path('messages', ClientMessagesView.as_view(), name='client-messages'),
    path('messages/', ClientMessagesView.as_view()),
    path('admin/automations', AdminAutomationsView.as_view(), name='admin-automations'),
    path('email/compose/', EmailComposeView.as_view(), name='email-compose'),
    path('admin/messages', AdminMessagesView.as_view(), name='admin-messages'),
    path('admin/messages/', AdminMessagesView.as_view()),
    path('admin/users', AdminUsersView.as_view(), name='admin-users'),
    path('admin/users/<str:pk>', AdminUsersView.as_view(), name='admin-user-detail'),
    path('platform-assistant/', PlatformAssistantView.as_view(), name='platform-assistant'),
    path('admin/settings/global', GlobalSettingsView.as_view(), name='global-settings'),
    path('webhook/whatsapp', WhatsAppWebhookView.as_view(), name='whatsapp-webhook'),
    path('webhook/whatsapp/', WhatsAppWebhookView.as_view()),
    path('webhooks/whatsapp', WhatsAppWebhookView.as_view()),
    path('webhooks/whatsapp/', WhatsAppWebhookView.as_view()),
    path('webhook/facebook-instagram', FacebookInstagramWebhookView.as_view(), name='facebook-instagram-webhook'),
    path('webhook/facebook-instagram/', FacebookInstagramWebhookView.as_view()),
    path('webhooks/facebook-instagram', FacebookInstagramWebhookView.as_view()),
    path('webhooks/facebook-instagram/', FacebookInstagramWebhookView.as_view()),
    # RAG Knowledge Base
    path('knowledge/', KnowledgeBaseView.as_view(), name='knowledge-base'),
    path('knowledge', KnowledgeBaseView.as_view()),
    path('knowledge/<str:pk>/', KnowledgeBaseView.as_view(), name='knowledge-base-detail'),
    path('knowledge/<str:pk>', KnowledgeBaseView.as_view()),
    path('admin/impersonate', AdminImpersonateView.as_view(), name='admin-impersonate'),
    path('admin/impersonate/', AdminImpersonateView.as_view()),
    # Razorpay / Cashfree Payments
    path('payments/create-order', CreatePaymentOrderView.as_view(), name='payment-create-order'),
    path('payments/create-order/', CreatePaymentOrderView.as_view()),
    path('payments/verify-order', VerifyPaymentView.as_view(), name='payment-verify-order'),
    path('payments/verify-order/', VerifyPaymentView.as_view()),
    path('payments/history', PaymentHistoryView.as_view(), name='payment-history'),
    path('payments/history/', PaymentHistoryView.as_view()),
    path('payments/webhook', RazorpayWebhookView.as_view(), name='payment-webhook'),
    path('payments/webhook/', RazorpayWebhookView.as_view()),
    # OneDrive Integration
    path('onedrive/connect', OneDriveConnectView.as_view(), name='onedrive-connect'),
    path('onedrive/connect/', OneDriveConnectView.as_view()),
    path('onedrive/callback', OneDriveCallbackView.as_view(), name='onedrive-callback'),
    path('onedrive/callback/', OneDriveCallbackView.as_view()),
    path('onedrive/status', OneDriveStatusView.as_view(), name='onedrive-status'),
    path('onedrive/status/', OneDriveStatusView.as_view()),
    path('onedrive/sync', OneDriveSyncView.as_view(), name='onedrive-sync'),
    path('onedrive/sync/', OneDriveSyncView.as_view()),
    path('onedrive/disconnect', OneDriveDisconnectView.as_view(), name='onedrive-disconnect'),
    path('onedrive/disconnect/', OneDriveDisconnectView.as_view()),
    # Google Calendar Integration
    path('google-calendar/connect', GoogleCalendarConnectView.as_view(), name='gcal-connect'),
    path('google-calendar/connect/', GoogleCalendarConnectView.as_view()),
    path('google-calendar/callback', GoogleCalendarCallbackView.as_view(), name='gcal-callback'),
    path('google-calendar/callback/', GoogleCalendarCallbackView.as_view()),
    path('google-calendar/status', GoogleCalendarStatusView.as_view(), name='gcal-status'),
    path('google-calendar/status/', GoogleCalendarStatusView.as_view()),
    path('google-calendar/sync', GoogleCalendarSyncView.as_view(), name='gcal-sync'),
    path('google-calendar/sync/', GoogleCalendarSyncView.as_view()),
    path('google-calendar/create-event', GoogleCalendarCreateEventView.as_view(), name='gcal-create-event'),
    path('google-calendar/create-event/', GoogleCalendarCreateEventView.as_view()),
    path('google-calendar/disconnect', GoogleCalendarDisconnectView.as_view(), name='gcal-disconnect'),
    path('google-calendar/disconnect/', GoogleCalendarDisconnectView.as_view()),
    # Google Sheets Integration
    path('google-sheets/connect', GoogleSheetsConnectView.as_view(), name='gsheets-connect'),
    path('google-sheets/connect/', GoogleSheetsConnectView.as_view()),
    path('google-sheets/callback', GoogleSheetsCallbackView.as_view(), name='gsheets-callback'),
    path('google-sheets/callback/', GoogleSheetsCallbackView.as_view()),
    path('google-sheets/status', GoogleSheetsStatusView.as_view(), name='gsheets-status'),
    path('google-sheets/status/', GoogleSheetsStatusView.as_view()),
    path('google-sheets/sync', GoogleSheetsSyncView.as_view(), name='gsheets-sync'),
    path('google-sheets/sync/', GoogleSheetsSyncView.as_view()),
    path('google-sheets/append-row', GoogleSheetsAppendRowView.as_view(), name='gsheets-append-row'),
    path('google-sheets/append-row/', GoogleSheetsAppendRowView.as_view()),
    path('google-sheets/disconnect', GoogleSheetsDisconnectView.as_view(), name='gsheets-disconnect'),
    path('google-sheets/disconnect/', GoogleSheetsDisconnectView.as_view()),
    # Google Docs Integration
    path('google-docs/connect', GoogleDocsConnectView.as_view(), name='gdocs-connect'),
    path('google-docs/connect/', GoogleDocsConnectView.as_view()),
    path('google-docs/callback', GoogleDocsCallbackView.as_view(), name='gdocs-callback'),
    path('google-docs/callback/', GoogleDocsCallbackView.as_view()),
    path('google-docs/status', GoogleDocsStatusView.as_view(), name='gdocs-status'),
    path('google-docs/status/', GoogleDocsStatusView.as_view()),
    path('google-docs/sync', GoogleDocsSyncView.as_view(), name='gdocs-sync'),
    path('google-docs/sync/', GoogleDocsSyncView.as_view()),
    path('google-docs/create-doc', GoogleDocsCreateDocView.as_view(), name='gdocs-create-doc'),
    path('google-docs/create-doc/', GoogleDocsCreateDocView.as_view()),
    path('google-docs/disconnect', GoogleDocsDisconnectView.as_view(), name='gdocs-disconnect'),
    path('google-docs/disconnect/', GoogleDocsDisconnectView.as_view()),
    # Google Slides Integration
    path('google-slides/connect', GoogleSlidesConnectView.as_view(), name='gslides-connect'),
    path('google-slides/connect/', GoogleSlidesConnectView.as_view()),
    path('google-slides/callback', GoogleSlidesCallbackView.as_view(), name='gslides-callback'),
    path('google-slides/callback/', GoogleSlidesCallbackView.as_view()),
    path('google-slides/status', GoogleSlidesStatusView.as_view(), name='gslides-status'),
    path('google-slides/status/', GoogleSlidesStatusView.as_view()),
    path('google-slides/sync', GoogleSlidesSyncView.as_view(), name='gslides-sync'),
    path('google-slides/sync/', GoogleSlidesSyncView.as_view()),
    path('google-slides/create-presentation', GoogleSlidesCreatePresentationView.as_view(), name='gslides-create-presentation'),
    path('google-slides/create-presentation/', GoogleSlidesCreatePresentationView.as_view()),
    path('google-slides/disconnect', GoogleSlidesDisconnectView.as_view(), name='gslides-disconnect'),
    # YouTube Integration
    path('auth/youtube/connect', YouTubeConnectView.as_view(), name='youtube-connect'),
    path('auth/youtube/callback', YouTubeCallbackView.as_view(), name='youtube-callback'),
    path('auth/youtube/status', YouTubeStatusView.as_view(), name='youtube-status'),
    path('auth/youtube/sync', YouTubeSyncView.as_view(), name='youtube-sync'),
    path('youtube/analytics', YouTubeAnalyticsView.as_view(), name='youtube-analytics'),
    path('youtube/analytics/', YouTubeAnalyticsView.as_view()),
    path('youtube/videos', YouTubeVideosView.as_view(), name='youtube-videos'),
    path('youtube/videos/', YouTubeVideosView.as_view()),
    path('youtube/comments', YouTubeCommentsView.as_view(), name='youtube-comments'),
    path('youtube/comments/', YouTubeCommentsView.as_view()),
    path('youtube/ai-suggest-reply', YouTubeAISuggestReplyView.as_view(), name='youtube-ai-suggest-reply'),
    path('youtube/ai-suggest-reply/', YouTubeAISuggestReplyView.as_view()),
    path('youtube/settings', YouTubeSettingsView.as_view(), name='youtube-settings'),
    path('youtube/settings/', YouTubeSettingsView.as_view()),
    path('youtube/broadcast-check', YouTubeCheckNewView.as_view(), name='youtube-broadcast-check'),
    path('youtube/broadcast-check/', YouTubeCheckNewView.as_view()),
    path('youtube/upload', YouTubeUploadView.as_view(), name='youtube-upload'),
    path('youtube/upload/', YouTubeUploadView.as_view()),
    path('youtube/profile', YouTubeChannelProfileView.as_view(), name='youtube-profile'),
    path('youtube/profile/', YouTubeChannelProfileView.as_view()),
    path('youtube/delete', YouTubeDeleteView.as_view(), name='youtube-delete'),
    path('youtube/delete/', YouTubeDeleteView.as_view()),
    path('google-slides/disconnect/', GoogleSlidesDisconnectView.as_view()),
    
    # Zoho Integration
    path('zoho/connect', ZohoConnectView.as_view(), name='zoho-connect'),
    path('zoho/connect/', ZohoConnectView.as_view()),
    path('zoho/callback', ZohoCallbackView.as_view(), name='zoho-callback'),
    path('zoho/callback/', ZohoCallbackView.as_view()),
    path('zoho/disconnect', ZohoDisconnectView.as_view(), name='zoho-disconnect'),
    path('zoho/disconnect/', ZohoDisconnectView.as_view()),
    path('zoho/test-lead', ZohoTestLeadView.as_view(), name='zoho-test-lead'),
    path('zoho/test-lead/', ZohoTestLeadView.as_view()),
    
    # Google News Integration
    path('google-news/settings', GoogleNewsSettingsView.as_view(), name='google-news-settings'),
    path('google-news/settings/', GoogleNewsSettingsView.as_view()),
    path('google-news/feed', GoogleNewsFeedView.as_view(), name='google-news-feed'),
    path('google-news/feed/', GoogleNewsFeedView.as_view()),
    path('google-news/summarize', GoogleNewsAISummarizeView.as_view(), name='google-news-summarize'),
    path('google-news/summarize/', GoogleNewsAISummarizeView.as_view()),
    path('google-news/send-alert', GoogleNewsSendAlertView.as_view(), name='google-news-send-alert'),
    path('google-news/send-alert/', GoogleNewsSendAlertView.as_view()),
    # Public endpoints
    path('public/calendar/<str:client_id>/slots', PublicCalendarSlotsView.as_view(), name='public-calendar-slots'),
    path('public/calendar/<str:client_id>/book', PublicCalendarBookView.as_view(), name='public-calendar-book'),

    # Microsoft Outlook Integration
    path('auth/outlook/connect', OutlookConnectView.as_view(), name='outlook-connect'),
    path('auth/outlook/connect/', OutlookConnectView.as_view()),
    path('auth/outlook/callback', OutlookCallbackView.as_view(), name='outlook-callback'),
    path('auth/outlook/callback/', OutlookCallbackView.as_view()),
    path('auth/outlook/status', OutlookStatusView.as_view(), name='outlook-status'),
    path('auth/outlook/status/', OutlookStatusView.as_view()),
    path('auth/outlook/sync', OutlookSyncView.as_view(), name='outlook-sync'),
    path('auth/outlook/sync/', OutlookSyncView.as_view()),
    path('auth/outlook/send-mail', OutlookSendMailView.as_view(), name='outlook-send-mail'),
    path('auth/outlook/send-mail/', OutlookSendMailView.as_view()),
    path('auth/outlook/disconnect', OutlookDisconnectView.as_view(), name='outlook-disconnect'),
    path('auth/outlook/disconnect/', OutlookDisconnectView.as_view()),
    path('auth/outlook/calendar/events', OutlookCalendarEventsView.as_view(), name='outlook-calendar-events'),
    path('auth/outlook/calendar/events/', OutlookCalendarEventsView.as_view()),
    path('auth/outlook/teams', OutlookTeamsView.as_view(), name='outlook-teams'),
    path('auth/outlook/teams/', OutlookTeamsView.as_view()),
    path('auth/outlook/contacts', OutlookContactsView.as_view(), name='outlook-contacts'),
    path('auth/outlook/contacts/', OutlookContactsView.as_view()),
    path('auth/outlook/excel', OutlookExcelView.as_view(), name='outlook-excel'),
    path('auth/outlook/excel/', OutlookExcelView.as_view()),

    # WebRTC & Calls Endpoints
    path('webrtc/config', WebRTCIceConfigView.as_view(), name='webrtc-config'),
    path('webrtc/config/', WebRTCIceConfigView.as_view()),
    path('webrtc/history', WebRTCHistoryView.as_view(), name='webrtc-history'),
    path('webrtc/history/', WebRTCHistoryView.as_view()),
    path('webrtc/call/initiate/', WebRTCInitiateCallView.as_view(), name='webrtc-call-initiate'),
    path('webrtc/call/action/', WebRTCCallActionView.as_view(), name='webrtc-call-action'),
    path('webrtc/call/signal/', WebRTCCallSignalView.as_view(), name='webrtc-call-signal'),
    path('webrtc/call/active-check', WebRTCActiveCallCheckView.as_view(), name='webrtc-call-active-check'),
    path('webrtc/call/active-check/', WebRTCActiveCallCheckView.as_view()),
    path('calls/schedule', CallScheduleView.as_view(), name='calls-schedule'),
    path('calls/schedule/', CallScheduleView.as_view()),
    path('calls/ai-summary', CallAISummaryView.as_view(), name='calls-ai-summary'),
    path('calls/ai-summary/', CallAISummaryView.as_view()),
    path('calls/analytics', CallAnalyticsView.as_view(), name='calls-analytics'),
    path('calls/analytics/', CallAnalyticsView.as_view()),

    # ── Per-Client Razorpay Gateway (OAuth / Technology Partner) ──────────────
    # Client OAuth connection
    path('razorpay/connect', RazorpayOAuthInitiateView.as_view(), name='razorpay-connect'),
    path('razorpay/connect/', RazorpayOAuthInitiateView.as_view()),
    path('razorpay/callback', RazorpayOAuthCallbackView.as_view(), name='razorpay-callback'),
    path('razorpay/callback/', RazorpayOAuthCallbackView.as_view()),
    # Connection management
    path('razorpay/status', RazorpayConnectionStatusView.as_view(), name='razorpay-status'),
    path('razorpay/status/', RazorpayConnectionStatusView.as_view()),
    path('razorpay/mode', RazorpayModeSwitchView.as_view(), name='razorpay-mode'),
    path('razorpay/mode/', RazorpayModeSwitchView.as_view()),
    # Product checkout (public — no auth needed for customer)
    path('razorpay/checkout/create-order', ProductCheckoutCreateOrderView.as_view(), name='razorpay-checkout-create'),
    path('razorpay/checkout/create-order/', ProductCheckoutCreateOrderView.as_view()),
    path('razorpay/checkout/verify', ProductCheckoutVerifyView.as_view(), name='razorpay-checkout-verify'),
    path('razorpay/checkout/verify/', ProductCheckoutVerifyView.as_view()),
    # Webhook (all workspaces, idempotent)
    path('razorpay/product-webhook', ProductCheckoutWebhookView.as_view(), name='razorpay-product-webhook'),
    path('razorpay/product-webhook/', ProductCheckoutWebhookView.as_view()),
    # Sales & analytics (authenticated client)
    path('razorpay/sales', ClientProductSalesView.as_view(), name='razorpay-sales'),
    path('razorpay/sales/', ClientProductSalesView.as_view()),
    path('razorpay/sales/dashboard', ClientSalesDashboardView.as_view(), name='razorpay-sales-dashboard'),
    path('razorpay/sales/dashboard/', ClientSalesDashboardView.as_view()),
    # Refunds
    path('razorpay/refund', ClientRefundView.as_view(), name='razorpay-refund'),
    path('razorpay/refund/', ClientRefundView.as_view()),
    # Public product checkout info (no auth — for customer-facing checkout page)
    path('public/checkout/<str:product_id>', PublicProductCheckoutInfoView.as_view(), name='public-checkout-info'),
    path('public/checkout/<str:product_id>/', PublicProductCheckoutInfoView.as_view()),
    
    # ── Sales Document Module (Quotations, Proposals, Invoices) ──
    path('sales/analytics', SalesAnalyticsView.as_view(), name='sales-analytics'),
    path('sales/analytics/', SalesAnalyticsView.as_view()),
    path('public/sales-documents/<str:token>', PublicSalesDocumentView.as_view(), name='public-sales-document-detail'),
    path('public/sales-documents/<str:token>/', PublicSalesDocumentView.as_view()),
    path('public/sales-documents/<str:token>/accept', PublicSalesDocumentAcceptView.as_view(), name='public-sales-document-accept'),
    path('public/sales-documents/<str:token>/accept/', PublicSalesDocumentAcceptView.as_view()),
    path('public/sales-documents/<str:token>/reject', PublicSalesDocumentRejectView.as_view(), name='public-sales-document-reject'),
    path('public/sales-documents/<str:token>/reject/', PublicSalesDocumentRejectView.as_view()),
    path('public/sales-documents/<str:token>/pdf', PublicSalesDocumentPDFView.as_view(), name='public-sales-document-pdf'),
    path('public/sales-documents/<str:token>/pdf/', PublicSalesDocumentPDFView.as_view()),

    path('public/quotation/<str:token>', PublicSalesDocumentView.as_view(), name='public-quotation-detail'),
    path('public/quotation/<str:token>/', PublicSalesDocumentView.as_view()),
    path('public/quotation/<str:token>/accept', PublicSalesDocumentAcceptView.as_view(), name='public-quotation-accept'),
    path('public/quotation/<str:token>/accept/', PublicSalesDocumentAcceptView.as_view()),
    path('public/quotation/<str:token>/reject', PublicSalesDocumentRejectView.as_view(), name='public-quotation-reject'),
    path('public/quotation/<str:token>/reject/', PublicSalesDocumentRejectView.as_view()),

    path('public/proposal/<str:token>', PublicSalesDocumentView.as_view(), name='public-proposal-detail'),
    path('public/proposal/<str:token>/', PublicSalesDocumentView.as_view()),
    path('public/proposal/<str:token>/accept', PublicSalesDocumentAcceptView.as_view(), name='public-proposal-accept'),
    path('public/proposal/<str:token>/accept/', PublicSalesDocumentAcceptView.as_view()),
    path('public/proposal/<str:token>/reject', PublicSalesDocumentRejectView.as_view(), name='public-proposal-reject'),
    path('public/proposal/<str:token>/reject/', PublicSalesDocumentRejectView.as_view()),

    # Public Invoice endpoints
    path('public/invoices/<str:token>', PublicInvoiceView.as_view(), name='public-invoice-detail'),
    path('public/invoices/<str:token>/', PublicInvoiceView.as_view()),
    path('public/invoices/<str:token>/pdf', PublicInvoicePDFView.as_view(), name='public-invoice-pdf'),
    path('public/invoices/<str:token>/pdf/', PublicInvoicePDFView.as_view()),
    path('public/invoice/<str:token>', PublicInvoiceView.as_view()),
    path('public/invoice/<str:token>/', PublicInvoiceView.as_view()),
    path('public/invoice/<str:token>/pdf', PublicInvoicePDFView.as_view()),
    path('public/invoice/<str:token>/pdf/', PublicInvoicePDFView.as_view()),

    # Channel & Connector Access Governance Endpoints
    path('admin/channel-access/global/', AdminGlobalConnectorsView.as_view(), name='admin-channel-access-global'),
    path('admin/channel-access/global', AdminGlobalConnectorsView.as_view()),
    path('admin/channel-access/global/<str:connector_key>/', AdminGlobalConnectorsView.as_view(), name='admin-channel-access-global-toggle'),
    path('admin/channel-access/global/<str:connector_key>', AdminGlobalConnectorsView.as_view()),
    path('admin/channel-access/matrix/', AdminChannelAccessMatrixView.as_view(), name='admin-channel-access-matrix'),
    path('admin/channel-access/matrix', AdminChannelAccessMatrixView.as_view()),
    path('admin/channel-access/client/<str:client_id>/', AdminClientChannelAccessDetailView.as_view(), name='admin-channel-access-client-detail'),
    path('admin/channel-access/client/<str:client_id>', AdminClientChannelAccessDetailView.as_view()),
    path('admin/channel-access/bulk/', AdminBulkChannelAccessView.as_view(), name='admin-channel-access-bulk'),
    path('admin/channel-access/bulk', AdminBulkChannelAccessView.as_view()),
    path('admin/channel-access/audit-logs/', AdminChannelAuditLogsView.as_view(), name='admin-channel-access-audit-logs'),
    path('admin/channel-access/audit-logs', AdminChannelAuditLogsView.as_view()),
    path('connectors/effective/', EffectiveConnectorsView.as_view(), name='connectors-effective'),
    path('connectors/effective', EffectiveConnectorsView.as_view()),
    path('connectors/global-status/', GlobalConnectorsStatusView.as_view(), name='connectors-global-status'),
    path('connectors/global-status', GlobalConnectorsStatusView.as_view()),

    # Admin Projects & Teams Endpoints
    path('admin/all-projects/', SuperAdminProjectsListView.as_view(), name='admin-all-projects'),
    path('admin/all-projects', SuperAdminProjectsListView.as_view()),
    path('admin/all-projects/<str:project_id>/', SuperAdminProjectDetailView.as_view(), name='admin-project-detail'),
    path('admin/all-projects/<str:project_id>', SuperAdminProjectDetailView.as_view()),
    path('admin/all-projects/<str:project_id>/assign/', SuperAdminProjectAssignMembersView.as_view(), name='admin-project-assign'),
    path('admin/all-projects/<str:project_id>/assign', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-projects/<str:project_id>/members/', SuperAdminProjectAssignMembersView.as_view(), name='admin-project-members'),
    path('admin/all-projects/<str:project_id>/members', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-projects/<str:project_id>/members/<str:member_id>/', SuperAdminProjectAssignMembersView.as_view(), name='admin-project-remove-member'),
    path('admin/all-projects/<str:project_id>/members/<str:member_id>', SuperAdminProjectAssignMembersView.as_view()),
    path('admin/all-team/', SuperAdminTeamListView.as_view(), name='admin-all-team'),
    path('admin/all-team', SuperAdminTeamListView.as_view()),
    path('admin/team-analytics/', SuperAdminTeamAnalyticsView.as_view(), name='admin-team-analytics'),
    path('admin/team-analytics', SuperAdminTeamAnalyticsView.as_view()),
    path('admin/teams-channels/', SuperAdminAllTeamsView.as_view(), name='admin-teams-channels'),
    path('admin/teams-channels', SuperAdminAllTeamsView.as_view()),
]
